const constants = {
  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  SET_SETTINGS: 'SET_SETTINGS',
  REMOVE_SETTINGS: 'REMOVE_SETTINGS',
  SET_SERVICES: 'SET_SERVICES',
  REMOVE_SERVICES: 'REMOVE_SERVICES',
  SET_CURRENT_SERVICE: 'SET_CURRENT_SERVICE',
  REMOVE_CURRENT_SERVICE: 'REMOVE_CURRENT_SERVICE',
  SET_VEHICLES: 'SET_VEHICLES',
  REMOVE_VEHICLES: 'REMOVE_VEHICLES',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  REMOVE_CURRENT_LOCATION: 'REMOVE_CURRENT_LOCATION',
  SET_CURRENT_CENTER: 'SET_CURRENT_CENTER',
  REMOVE_CURRENT_CENTER: 'REMOVE_CURRENT_CENTER',
  SET_DESTINATION: 'SET_DESTINATION',
  REMOVE_DESTINATION: 'REMOVE_DESTINATION',
  SET_PLAYBACK_LOCATIONS: 'SET_PLAYBACK_LOCATIONS',
  REMOVE_PLAYBACK_LOCATIONS: 'REMOVE_PLAYBACK_LOCATIONS',
  SHOW_PLAYBACK_BUTTON: 'SHOW_PLAYBACK_BUTTON',
  SHOW_OTHER_BUTTONS: 'SHOW_OTHER_BUTTONS',
  OPEN_PLAYBACK_DIALOG: 'OPEN_PLAYBACK_DIALOG',
  CLOSE_PLAYBACK_DIALOG: 'CLOSE_PLAYBACK_DIALOG'
};

export default constants;
